#!/usr/bin/env bash

function recipe {
  local nm_recipe="$1"; shift
  set --
  source "$nm_recipe"
}

function install_options {
  if [[ -n "$_poop_mode" ]]; then
    echo -n "-m $_poop_mode "
  fi

  if [[ -n "$_poop_owner" ]]; then
    echo -n "-o $_poop_owner"
  fi

  if [[ -n "$_poop_group" ]]; then
    echo -n "-g $_poop_group"
  fi
}
