#!/usr/bin/env bash

function template {
  _poop_name="$1"; shift
  _poop_ing="$FUNCNAME"
}

function do_template {
  : ${_poop_action:=create}
  : ${_poop_path:=${_poop_name}}

  "do_${_poop_ing}_${_poop_action}"
}

function do_template_create {
  local pth_source="${_poop_sauce}"

  local tmp_template="$(mktemp -t XXXXXXXXX)"
  cat "${pth_source}" | envsubst > "$tmp_template"
  install -v $(install_options)"$tmp_template" "${_poop_path}"
  rm -f "$tmp_template"
}
