#!/bin/bash

function file {
  _poop_name="$1"; shift
  _poop_ing="$FUNCNAME"
}

function do_file {
  : ${_poop_action:=create}
  : ${_poop_path:=${_poop_name}}

  "do_${_poop_ing}_${_poop_action}"
}

function do_file_create {
  touch -v "${_poop_path}"
}

function do_file_delete {
  rm -vf "${_poop_path}"
}
