#!/usr/bin/env bash

function poop_bootstrap {
  local shome="${_poop_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"

  pkg ensure misc/toilet
}

poop_bootstrap "$@"
