#!/usr/bin/env bash

function poop_bootstrap {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  pkg ensure misc/toilet
  pkg ensure devel/gettext-tools
}

poop_bootstrap "$@"
